name: Test Go Version Setup

on: [push, pull_request]

jobs:
  test-go-setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Display Go version
        run: go version

      - name: Display Latest Go version
        run: |
          latest_go_version=$(curl -s https://go.dev/VERSION?m=text)
          echo "Latest Go version: $latest_go_version"

      - name: Run Go build
        run: go build -v ./...
